services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"     
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - frontend_dist:/frontend/dist:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - project-network
      - caddy


networks:
  project-network:
    driver: bridge
  caddy:
    external: true
    name: caddy
    driver: bridge
    
volumes:
  frontend_dist:
    external: true
  caddy_data:
  caddy_config: