services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - frontend_dist:/frontend/dist:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - project-network
    depends_on:
      - project_frontend
      - project_backend

networks:
  project-network:
    driver: bridge

volumes:
  frontend_dist:
    external: true
  caddy_data:
  caddy_config: