services:
  caddy:
    container_name: caddy
    image: caddy:alpine
    # publish everything you deem necessary
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    networks:
      - caddy
    restart: unless-stopped
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - config:/config
      - data:/data

networks:
  caddy:
    name: caddy

volumes:
  config:
  data:
